name: ProyectoFinalLibreriaUSFQ
description: "Aplicación de biblioteca para USFQ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Base de datos
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # State management
  provider: ^6.1.1
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  
  # API y Networking
  http: ^1.1.0
  
  # AI
  google_generative_ai: ^0.2.0
  
  # Utils
  uuid: ^4.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.2.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/library.png
    - assets/photo.png